CREATE TABLE IF NOT EXISTS Users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(512) NOT NULL,
    is_admin BOOL NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS Devices (
    ip VARCHAR(16) PRIMARY KEY UNIQUE,
    hostname VARCHAR(128) DEFAULT '',
    name VARCHAR(255) DEFAULT '',
    is_doorbell BOOLEAN NOT NULL DEFAULT FALSE
);